name: office Flow

on:
  push:
    paths:
      - 'Records/officeFlow.txt'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#############################################################################################    
       - name: Checkout
         uses: actions/checkout@main
############################################################################################# 
       - name: Initialization
         continue-on-error: true
         run: |
           git config --global user.name ${{ secrets.GH_NAME }}
           git config --global user.email ${{ secrets.GH_MAIL }}
           git config --global credential.helper store
           echo "https://rocket-boys:${{ secrets.github.token }}@github.com" > ~/.git-credentials
############################################################################################# 
       - name: Apt Update packages and Upgrade them.
         run: |
            sudo su && sudo apt update -y && sudo apt upgrade -y
#############################################################################################
       - name: Install ct
         run: |
              curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb 
              sudo dpkg -i cloudflared.deb 
              sudo cloudflared service install ${{ secrets.CF_T }}
#############################################################################################
       - uses: styfle/cancel-workflow-action@0.9.0
         name: "Cancel duplicate workflow runs"
         with:
            all_but_latest: true
            access_token: ${{ secrets.GH_TOKEN }}
#############################################################################################
       - name: Sleep for 30 secs to kill previous contianer
         run: sleep 30s
         shell: bash
#############################################################################################
       - name: Deploying and Running Office Flow
         timeout-minutes: 300
         continue-on-error: true
         run: |
           git clone https://rocket-boys:${{ secrets.GH_TOKEN }}@github.com/rocket-boys/office office && cd office && sudo docker-compose up --build
#############################################################################################
       - name: Send Record to Github
         continue-on-error: true
         run: |
              git clone https://github.com/rocket-boys/spaceflow
              cd spaceflow || exit 1
              echo $(TZ='${{ secrets.TZ }}' date) >> Records/officeFlow.txt
              git add Records/officeFlow.txt
              git commit -m "office Workflow : add recorded loop to logs $(TZ='${{ secrets.TZ }}' date)"
              git push -q https://${{ secrets.GH_TOKEN }}@github.com/rocket-boys/spaceflow HEAD:main            
